{
	"object_list": [{
		"id": 230,
		"network": "twitter",
		"all_text": "This is country music brother @tylerfarr #AGuyWalksIntoABar http://t.co/bbZYMNjAMy",
		"post_id": "494646936910057473",
		"post_date": "2014-07-31T00:53:14Z",
		"post_type": "photo",
		"poster_sn": "FLAGALine",
		"poster_name": "Florida Georgia Line",
		"poster_id": "158014897",
		"avatar_url": "http://pbs.twimg.com/profile_images/486424739716423680/ZNp-3eL0_normal.jpeg",
		"image_url": "http://pbs.twimg.com/media/Bt1WxFOCQAA0XmB.jpg",
		"image_width": 576,
		"image_height": 1024,
		"image_caption": "",
		"title": "",
		"body": "This is country music brother <a href='http://twitter.com/tylerfarr' target='_blank'>@tylerfarr </a> <a href='http://twitter.com/search?q=%23AGuyWalksIntoABar' target='_blank'>#AGuyWalksIntoABar </a> <a href=\"http://t.co/bbZYMNjAMy\" target=\"_blank\">pic.twitter.com/bbZYMNjAMy </a>",
		"link_url": "",
		"link_title": ""
	}, {
		"id": 229,
		"network": "twitter",
		"all_text": "Tune in to CMA Music Fest: Country’s Night to Rock on 8/5! See Backstage Access artist @MirandaLambert+more #CMAfest http://t.co/d8b7Yl6q2p",
		"post_id": "494528442332106752",
		"post_date": "2014-07-30T17:02:23Z",
		"post_type": "text",
		"poster_sn": "countrymusichof",
		"poster_name": "Country Music HOF",
		"poster_id": "18088267",
		"avatar_url": "http://pbs.twimg.com/profile_images/479358706388197376/jB1Y3Aj2_normal.png",
		"image_url": "",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "Tune in to CMA Music Fest: Country’s Night to Rock on 8/5! See Backstage Access artist <a href='http://twitter.com/MirandaLambert' target='_blank'>@MirandaLambert </a>+more <a href='http://twitter.com/search?q=%23CMAfest' target='_blank'>#CMAfest </a> <a href=\"http://t.co/d8b7Yl6q2p\" target=\"_blank\">ow.ly/i/6o42e </a>",
		"link_url": "",
		"link_title": ""
	}, {
		"id": 228,
		"network": "youtube",
		"all_text": "colt ford received his first academy of country music awards nomination this year for his collaboration with jamey johnson on the tune  cold beer   he didn t    colt ford rocks the acm s ",
		"post_id": "Ov9e4H18qc8",
		"post_date": "2014-06-10T04:00:25Z",
		"post_type": "video",
		"poster_sn": "Colt Ford",
		"poster_name": "",
		"poster_id": "u0xqt7g2nkdwg8l96VVqiA",
		"avatar_url": "https://i2.ytimg.com/i/u0xqt7g2nkdwg8l96VVqiA/1.jpg",
		"image_url": "https://i.ytimg.com/vi/Ov9e4H18qc8/3.jpg",
		"image_width": 120,
		"image_height": 90,
		"image_caption": "",
		"title": "Colt Ford Rocks the ACM's!",
		"body": "Colt Ford received his first Academy of Country Music Awards nomination this year for his collaboration with Jamey Johnson on the tune \"Cold Beer\". He didn't...",
		"link_url": "http://www.youtube.com/watch?v=Ov9e4H18qc8",
		"link_title": ""
	}, {
		"id": 226,
		"network": "facebook",
		"all_text": "check out the people com exclusive preview of  crushin  it  here \n\nhttp   www people com article brad paisley crushin it off moonshine in the trunk listen to brad paisley s new song  crushin  it  – legally  www people com the singer shares a preview of his new tune exclusively with people country",
		"post_id": "6791933097_10153022780803098",
		"post_date": "2014-07-29T23:31:32Z",
		"post_type": "photo",
		"poster_sn": "Brad Paisley",
		"poster_name": "",
		"poster_id": "6791933097",
		"avatar_url": "https://graph.facebook.com/6791933097/picture",
		"image_url": "http://img2-2.timeinc.net/people/i/2014/country/blog/140630/brad-paisley-300.jpg",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "Check out the People.com exclusive preview of \"Crushin' It\" here:\n\nhttp://www.people.com/article/brad-paisley-crushin-it-off-moonshine-in-the-trunk",
		"link_url": "http://www.people.com/article/brad-paisley-crushin-it-off-moonshine-in-the-trunk",
		"link_title": "Listen to Brad Paisley's New Song 'Crushin' It' – Legally!"
	}, {
		"id": 227,
		"network": "youtube",
		"all_text": "the official music video for colt ford s  country thang   directed by potsy ponciroli  the new album   every chance i get   is in stores now  you can also he    colt ford   country thang   official video",
		"post_id": "NEYzcEM2zSU",
		"post_date": "2014-07-27T21:00:33Z",
		"post_type": "video",
		"poster_sn": "Colt Ford",
		"poster_name": "",
		"poster_id": "u0xqt7g2nkdwg8l96VVqiA",
		"avatar_url": "https://i2.ytimg.com/i/u0xqt7g2nkdwg8l96VVqiA/1.jpg",
		"image_url": "https://i.ytimg.com/vi/NEYzcEM2zSU/3.jpg",
		"image_width": 120,
		"image_height": 90,
		"image_caption": "",
		"title": "Colt Ford - Country Thang - Official Video",
		"body": "The official music video for Colt Ford's \"Country Thang\"! Directed by Potsy Ponciroli. The new album, 'Every Chance I Get', is in stores now! You can also he...",
		"link_url": "http://www.youtube.com/watch?v=NEYzcEM2zSU",
		"link_title": ""
	}, {
		"id": 225,
		"network": "facebook",
		"all_text": "oh no  it s a close one  me and buds dan   shay are battling it out on taste of country      http   tasteofcountry com jerrod niemann dan shay the showdown    if ya can get a chance  please check it out   cheers  dehydrationnation  thanksforthelove jerrod niemann vs  dan   shay   the showdown tasteofcountry com on friday jerrod niemann s new song from  high noon  took on the latest from jake owen  and thumped him   buzz back girl  moves on to a new round in this thrice weekly song battle  the track will face the latest from dan   shay today and tuesday ",
		"post_id": "113965198623141_836444473041873",
		"post_date": "2014-07-29T19:52:02Z",
		"post_type": "photo",
		"poster_sn": "Jerrod Niemann",
		"poster_name": "",
		"poster_id": "113965198623141",
		"avatar_url": "https://graph.facebook.com/113965198623141/picture",
		"image_url": "http://wac.450f.edgecastcdn.net/80450F/tasteofcountry.com/files/2014/07/Showdown.jpg?w=600&h=0&zc=1&s=0&a=t&q=89",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "Oh no, it's a close one! Me and buds Dan & Shay are battling it out on Taste Of Country. :)  http://tasteofcountry.com/jerrod-niemann-dan-shay-the-showdown/ . If ya can get a chance, please check it out. #cheers #dehydrationnation #thanksforthelove",
		"link_url": "http://tasteofcountry.com/jerrod-niemann-dan-shay-the-showdown/",
		"link_title": "Jerrod Niemann vs. Dan + Shay - The Showdown"
	}, {
		"id": 224,
		"network": "twitter",
		"all_text": "Somebody had to make a difference in country music... So god made @RaeLynnOfficial. So proud to say you're my friend. I love you baby girl.",
		"post_id": "493580255861276673",
		"post_date": "2014-07-28T02:14:37Z",
		"post_type": "text",
		"poster_sn": "blakeshelton",
		"poster_name": "Blake Shelton",
		"poster_id": "14920785",
		"avatar_url": "http://pbs.twimg.com/profile_images/484437394121183232/kxglaz8f_normal.jpeg",
		"image_url": "",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "Somebody had to make a difference in country music... So god made <a href='http://twitter.com/RaeLynnOfficial' target='_blank'>@RaeLynnOfficial </a>. So proud to say you're my friend. I love you baby girl.",
		"link_url": "",
		"link_title": ""
	}, {
		"id": 223,
		"network": "facebook",
		"all_text": "what better way to spend your birthday than a game of cornhole with fans and friends and doin what i love the most  playing some country music  thank you all for the birthday wishes  am a lucky guy   cheers   raiseemuptour",
		"post_id": "113965198623141_834016206618033",
		"post_date": "2014-07-25T02:30:00Z",
		"post_type": "photo",
		"poster_sn": "Jerrod Niemann",
		"poster_name": "",
		"poster_id": "113965198623141",
		"avatar_url": "https://graph.facebook.com/113965198623141/picture",
		"image_url": "https://fbcdn-sphotos-c-a.akamaihd.net/hphotos-ak-xpa1/t1.0-9/p540x540/10414508_833979176621736_8381116238323715421_n.jpg",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "What better way to spend your birthday than a game of cornhole with fans and friends and doin what I love the most, playing some country music! Thank you all for the birthday wishes, am a lucky guy! #cheers  #RaiseEmUpTour",
		"link_url": "https://www.facebook.com/JerrodNiemann/photos/a.226247707394889.67433.113965198623141/833979176621736/?type=1&relevant_count=1",
		"link_title": ""
	}, {
		"id": 222,
		"network": "facebook",
		"all_text": "miranda gives a tour of her home away from home   the tour bus  miranda lambert  life on the road with a country superstar www usatoday com the  automatic  singer takes us behind the scenes of her tour and discusses her new music ",
		"post_id": "5764270741_10152590166140742",
		"post_date": "2014-07-23T19:56:59Z",
		"post_type": "photo",
		"poster_sn": "Miranda Lambert",
		"poster_name": "",
		"poster_id": "5764270741",
		"avatar_url": "https://graph.facebook.com/5764270741/picture",
		"image_url": "http://www.gannett-cdn.com/-mm-/be09fab3c95fd6c644b9e56e968481187393bbcb/c=0-493-4928-3272&r=x1803&c=3200x1800/local/-/media/USATODAY/USATODAY/2014/07/23/1406126322000-Miranda.jpeg",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "Miranda gives a tour of her home away from home - the tour bus!",
		"link_url": "http://www.usatoday.com/story/experience/weekend/entertainment/2014/07/23/miranda-lambert-life-on-the-road-with-a-country-superstar/13039681/",
		"link_title": "Miranda Lambert: Life on the road with a country superstar"
	}, {
		"id": 221,
		"network": "twitter",
		"all_text": "Thank you Taste of Country for the lyrics uncovered on \"Dirt\".  Proud of Rodney Clawson and Chris Tompkins.... http://t.co/9XSuOQ8ybc",
		"post_id": "491972813079592960",
		"post_date": "2014-07-23T15:47:13Z",
		"post_type": "text",
		"poster_sn": "FLAGALine",
		"poster_name": "Florida Georgia Line",
		"poster_id": "158014897",
		"avatar_url": "http://pbs.twimg.com/profile_images/486424739716423680/ZNp-3eL0_normal.jpeg",
		"image_url": "",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "Thank you Taste of Country for the lyrics uncovered on \"Dirt\".  Proud of Rodney Clawson and Chris Tompkins.... <a href=\"http://t.co/9XSuOQ8ybc\" target=\"_blank\">fb.me/6M4baMom0 </a>",
		"link_url": "",
		"link_title": ""
	}, {
		"id": 220,
		"network": "twitter",
		"all_text": "Well deserved, great job.I wanna hear you sing a country song next! RT @AustinFrench316:thanks so much for that awesome and humbling comment",
		"post_id": "491483564148408323",
		"post_date": "2014-07-22T07:23:07Z",
		"post_type": "text",
		"poster_sn": "BradPaisley",
		"poster_name": "Brad Paisley",
		"poster_id": "41265813",
		"avatar_url": "http://pbs.twimg.com/profile_images/483027014832500736/rjcKrWYB_normal.jpeg",
		"image_url": "",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "Well deserved, great job.I wanna hear you sing a country song next! RT <a href='http://twitter.com/AustinFrench316' target='_blank'>@AustinFrench316 </a>:thanks so much for that awesome and humbling comment",
		"link_url": "",
		"link_title": ""
	}, {
		"id": 219,
		"network": "twitter",
		"all_text": "Country Explosion 2014 ROCKED! Did a little mountain biking during the day, enjoyed some of the beautiful scenery... http://t.co/cA1KTsNQA7",
		"post_id": "491459011024547840",
		"post_date": "2014-07-22T05:45:33Z",
		"post_type": "text",
		"poster_sn": "FLAGALine",
		"poster_name": "Florida Georgia Line",
		"poster_id": "158014897",
		"avatar_url": "http://pbs.twimg.com/profile_images/486424739716423680/ZNp-3eL0_normal.jpeg",
		"image_url": "",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "Country Explosion 2014 ROCKED! Did a little mountain biking during the day, enjoyed some of the beautiful scenery... <a href=\"http://t.co/cA1KTsNQA7\" target=\"_blank\">fb.me/3pWfMNY98 </a>",
		"link_url": "",
		"link_title": ""
	}, {
		"id": 218,
		"network": "twitter",
		"all_text": "Country Explosion 2014 ROCKED! Did a little mountain biking during the day, enjoyed some of the beautiful scenery... http://t.co/LKY58O2kWn",
		"post_id": "491459235579195392",
		"post_date": "2014-07-22T05:46:27Z",
		"post_type": "text",
		"poster_sn": "FLAGALine",
		"poster_name": "Florida Georgia Line",
		"poster_id": "158014897",
		"avatar_url": "http://pbs.twimg.com/profile_images/486424739716423680/ZNp-3eL0_normal.jpeg",
		"image_url": "",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "Country Explosion 2014 ROCKED! Did a little mountain biking during the day, enjoyed some of the beautiful scenery... <a href=\"http://t.co/LKY58O2kWn\" target=\"_blank\">fb.me/3peS62DXX </a>",
		"link_url": "",
		"link_title": ""
	}, {
		"id": 217,
		"network": "twitter",
		"all_text": "♫ Today: Tooele, UT - Jul 20 at Country Explosion - Deseret Peak Complex http://t.co/3o6kIurNne",
		"post_id": "490964850915688449",
		"post_date": "2014-07-20T21:01:56Z",
		"post_type": "text",
		"poster_sn": "FLAGALine",
		"poster_name": "Florida Georgia Line",
		"poster_id": "158014897",
		"avatar_url": "http://pbs.twimg.com/profile_images/486424739716423680/ZNp-3eL0_normal.jpeg",
		"image_url": "",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "♫ Today: Tooele, UT - Jul 20 at Country Explosion - Deseret Peak Complex <a href=\"http://t.co/3o6kIurNne\" target=\"_blank\">bandsintown.com/event/7385075?… </a>",
		"link_url": "",
		"link_title": ""
	}, {
		"id": 216,
		"network": "twitter",
		"all_text": "Love seeing COUNTRY Music have two songs in the top 10 all genre on @iTunesMusic - very proud to be apart of this... http://t.co/KzDuHhIvjf",
		"post_id": "490936511227908096",
		"post_date": "2014-07-20T19:09:20Z",
		"post_type": "text",
		"poster_sn": "FLAGALine",
		"poster_name": "Florida Georgia Line",
		"poster_id": "158014897",
		"avatar_url": "http://pbs.twimg.com/profile_images/486424739716423680/ZNp-3eL0_normal.jpeg",
		"image_url": "",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "Love seeing COUNTRY Music have two songs in the top 10 all genre on <a href='http://twitter.com/iTunesMusic' target='_blank'>@iTunesMusic </a> - very proud to be apart of this... <a href=\"http://t.co/KzDuHhIvjf\" target=\"_blank\">fb.me/1gltugp23 </a>",
		"link_url": "",
		"link_title": ""
	}, {
		"id": 214,
		"network": "twitter",
		"all_text": "We feel on top of our game because of you, our amazing fans, country radio's support, and our bad ass team. #fglislife new music comin baby",
		"post_id": "490908597677600768",
		"post_date": "2014-07-20T17:18:24Z",
		"post_type": "text",
		"poster_sn": "FLAGALine",
		"poster_name": "Florida Georgia Line",
		"poster_id": "158014897",
		"avatar_url": "http://pbs.twimg.com/profile_images/486424739716423680/ZNp-3eL0_normal.jpeg",
		"image_url": "",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "We feel on top of our game because of you, our amazing fans, country radio's support, and our bad ass team. <a href='http://twitter.com/search?q=%23fglislife' target='_blank'>#fglislife </a> new music comin baby",
		"link_url": "",
		"link_title": ""
	}, {
		"id": 215,
		"network": "twitter",
		"all_text": "Love seeing COUNTRY Music have two songs in the top 10 all genre on @iTunesMusic - very proud to be apart of this... http://t.co/PHhQSjbrIp",
		"post_id": "490936804783423488",
		"post_date": "2014-07-20T19:10:30Z",
		"post_type": "text",
		"poster_sn": "FLAGALine",
		"poster_name": "Florida Georgia Line",
		"poster_id": "158014897",
		"avatar_url": "http://pbs.twimg.com/profile_images/486424739716423680/ZNp-3eL0_normal.jpeg",
		"image_url": "",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "Love seeing COUNTRY Music have two songs in the top 10 all genre on <a href='http://twitter.com/iTunesMusic' target='_blank'>@iTunesMusic </a> - very proud to be apart of this... <a href=\"http://t.co/PHhQSjbrIp\" target=\"_blank\">fb.me/6F0zKxUyG </a>",
		"link_url": "",
		"link_title": ""
	}, {
		"id": 213,
		"network": "facebook",
		"all_text": "miranda and carrie underwood are up for a new fox teen choice awards category   choice country summer song  vote for this and choice female country artist now  \n\nwww teenchoiceawards com",
		"post_id": "5764270741_10152578637500742",
		"post_date": "2014-07-18T19:26:30Z",
		"post_type": "photo",
		"poster_sn": "Miranda Lambert",
		"poster_name": "",
		"poster_id": "5764270741",
		"avatar_url": "https://graph.facebook.com/5764270741/picture",
		"image_url": "https://scontent-a.xx.fbcdn.net/hphotos-xfp1/t1.0-9/s540x540/10565052_10152578637090742_1525404162737024119_n.jpg",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "Miranda and Carrie Underwood are up for a new FOX Teen Choice Awards category - Choice Country Summer Song! Vote for this and Choice Female Country Artist NOW! \n\nwww.teenchoiceawards.com",
		"link_url": "https://www.facebook.com/photo.php?fbid=10152578637090742&set=a.393516945741.171002.5764270741&type=1&relevant_count=1",
		"link_title": ""
	}, {
		"id": 212,
		"network": "facebook",
		"all_text": " every time i fall i get back up again\ncinch my saddle up and find me another wind\nlet it take me where it wants to go\nanother one horse town  another damned old rodeo        randy houser   like a cowboy  full length version   like a cowboy   full length version  from how country feels  available here  http   smarturl it howcountyfeels directed by dustin rikert  a team two enterta   ",
		"post_id": "49064345453_10154447331565454",
		"post_date": "2014-07-16T20:07:15Z",
		"post_type": "photo",
		"poster_sn": "Randy Houser",
		"poster_name": "",
		"poster_id": "49064345453",
		"avatar_url": "https://graph.facebook.com/49064345453/picture",
		"image_url": "http://i1.ytimg.com/vi/Gn_m7uFL7xQ/maxresdefault.jpg",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "\"Every time I fall I get back up again\nCinch my saddle up and find me another wind\nLet it take me where it wants to go\nAnother one horse town, another damned old rodeo . . .\"",
		"link_url": "http://www.youtube.com/watch?v=Gn_m7uFL7xQ",
		"link_title": "Randy Houser - Like a Cowboy (Full Length Version)"
	}, {
		"id": 211,
		"network": "youtube",
		"all_text": "tim performs  down on the farm  up close and personal to the crowd tim mcgraw s single  lookin  for that girl  now available on itunes  http   smarturl it tm    tim mcgraw   may 2010 concert footage   country boys and girls",
		"post_id": "HSIv7Ub_tFw",
		"post_date": "2014-05-12T18:20:41Z",
		"post_type": "video",
		"poster_sn": "timmcgraw",
		"poster_name": "",
		"poster_id": "2mK990tp7umnN6Y-DEGpDg",
		"avatar_url": "https://i2.ytimg.com/i/2mK990tp7umnN6Y-DEGpDg/1.jpg",
		"image_url": "https://i.ytimg.com/vi/HSIv7Ub_tFw/3.jpg",
		"image_width": 120,
		"image_height": 90,
		"image_caption": "",
		"title": "Tim McGraw - May 2010 concert footage - Country Boys and Girls",
		"body": "Tim performs \"Down On the Farm\" up close and personal to the crowd Tim McGraw's single \"Lookin' For That Girl\" now available on iTunes: http://smarturl.it/TM...",
		"link_url": "http://www.youtube.com/watch?v=HSIv7Ub_tFw",
		"link_title": ""
	}, {
		"id": 204,
		"network": "youtube",
		"all_text": "watch wynonna and colt chat about the song  never thought  from ride through the country  revisited   download the song on itunes  http   smarturl it rttcrev    wynonna behind the scenes with colt ford singing  never thought ",
		"post_id": "EsC6cxGE5WM",
		"post_date": "2014-02-25T19:51:42Z",
		"post_type": "video",
		"poster_sn": "Colt Ford",
		"poster_name": "",
		"poster_id": "u0xqt7g2nkdwg8l96VVqiA",
		"avatar_url": "https://i2.ytimg.com/i/u0xqt7g2nkdwg8l96VVqiA/1.jpg",
		"image_url": "https://i.ytimg.com/vi/EsC6cxGE5WM/3.jpg",
		"image_width": 120,
		"image_height": 90,
		"image_caption": "",
		"title": "Wynonna Behind the Scenes with Colt Ford singing \"Never Thought\"",
		"body": "Watch Wynonna and Colt chat about the song \"Never Thought\" from Ride Through the Country (Revisited). Download the song on iTunes: http://smarturl.it/RTTCRev...",
		"link_url": "http://www.youtube.com/watch?v=EsC6cxGE5WM",
		"link_title": ""
	}, {
		"id": 210,
		"network": "youtube",
		"all_text": "trailer for  country strong  starring tim mcgraw  gwyneth paltrow  leighton meester and garrett hedlund  in theaters nationwide january 7  2011  tim mcgraw s    country strong trailer",
		"post_id": "2-Dqp6mJtOM",
		"post_date": "2014-02-25T20:19:57Z",
		"post_type": "video",
		"poster_sn": "timmcgraw",
		"poster_name": "",
		"poster_id": "2mK990tp7umnN6Y-DEGpDg",
		"avatar_url": "https://i2.ytimg.com/i/2mK990tp7umnN6Y-DEGpDg/1.jpg",
		"image_url": "https://i.ytimg.com/vi/2-Dqp6mJtOM/3.jpg",
		"image_width": 120,
		"image_height": 90,
		"image_caption": "",
		"title": "Country Strong Trailer",
		"body": "Trailer for 'Country Strong' starring Tim McGraw, Gwyneth Paltrow, Leighton Meester and Garrett Hedlund. In theaters nationwide January 7, 2011. Tim McGraw's...",
		"link_url": "http://www.youtube.com/watch?v=2-Dqp6mJtOM",
		"link_title": ""
	}, {
		"id": 208,
		"network": "youtube",
		"all_text": "country weekly is on the hunt for the sexiest man in country music and they seem to have forgotten colt ford from the ballot  write this wrong by voting for     colt ford sexiest man in country music",
		"post_id": "6OnHSrqp3xc",
		"post_date": "2014-06-27T19:10:48Z",
		"post_type": "video",
		"poster_sn": "Colt Ford",
		"poster_name": "",
		"poster_id": "u0xqt7g2nkdwg8l96VVqiA",
		"avatar_url": "https://i2.ytimg.com/i/u0xqt7g2nkdwg8l96VVqiA/1.jpg",
		"image_url": "https://i.ytimg.com/vi/6OnHSrqp3xc/3.jpg",
		"image_width": 120,
		"image_height": 90,
		"image_caption": "",
		"title": "Colt Ford Sexiest Man In Country Music",
		"body": "Country Weekly is on the hunt for the sexiest man in country music and they seem to have forgotten Colt Ford from the ballot! Write this wrong by voting for ...",
		"link_url": "http://www.youtube.com/watch?v=6OnHSrqp3xc",
		"link_title": ""
	}, {
		"id": 209,
		"network": "youtube",
		"all_text": "music video for  for the outlawz  performed by outlaw country   hip hop rebels moonshine bandits featuring colt ford and big b  the song is just a swig of wh    moonshine bandits feat colt ford  for the outlawz ",
		"post_id": "DDQo6qiFs9o",
		"post_date": "2014-07-13T06:53:53Z",
		"post_type": "video",
		"poster_sn": "Colt Ford",
		"poster_name": "",
		"poster_id": "u0xqt7g2nkdwg8l96VVqiA",
		"avatar_url": "https://i2.ytimg.com/i/u0xqt7g2nkdwg8l96VVqiA/1.jpg",
		"image_url": "https://i.ytimg.com/vi/DDQo6qiFs9o/3.jpg",
		"image_width": 120,
		"image_height": 90,
		"image_caption": "",
		"title": "Moonshine Bandits feat Colt Ford \"For the Outlawz\"",
		"body": "Music Video for \"For The Outlawz\" performed by Outlaw Country & Hip-Hop Rebels Moonshine Bandits featuring Colt Ford and Big B. The song is just a swig of wh...",
		"link_url": "http://www.youtube.com/watch?v=DDQo6qiFs9o",
		"link_title": ""
	}, {
		"id": 203,
		"network": "youtube",
		"all_text": "relive 2013 with colt ford and crew as they travel the country  download all the latest colt ford music on itunes  https   itunes apple com us artist colt fo    rewind with colt ford   relive your favorite moments from 2013",
		"post_id": "hiRUa5S93Nk",
		"post_date": "2014-07-15T04:07:03Z",
		"post_type": "video",
		"poster_sn": "Colt Ford",
		"poster_name": "",
		"poster_id": "u0xqt7g2nkdwg8l96VVqiA",
		"avatar_url": "https://i2.ytimg.com/i/u0xqt7g2nkdwg8l96VVqiA/1.jpg",
		"image_url": "https://i.ytimg.com/vi/hiRUa5S93Nk/3.jpg",
		"image_width": 120,
		"image_height": 90,
		"image_caption": "",
		"title": "Rewind with Colt Ford!  Relive your favorite moments from 2013",
		"body": "Relive 2013 with Colt Ford and crew as they travel the country! Download all the latest Colt Ford music on iTunes: https://itunes.apple.com/us/artist/colt-fo...",
		"link_url": "http://www.youtube.com/watch?v=hiRUa5S93Nk",
		"link_title": ""
	}, {
		"id": 205,
		"network": "youtube",
		"all_text": "download ride through the country  revisited  on itunes today  http   smarturl it rttcrevisiteditunes watch as colt ford and his band bring colt s classic de    ride through the country  revisited    the making of the album   colt ford",
		"post_id": "Fanxe0Oi6BE",
		"post_date": "2014-05-22T05:57:21Z",
		"post_type": "video",
		"poster_sn": "Colt Ford",
		"poster_name": "",
		"poster_id": "u0xqt7g2nkdwg8l96VVqiA",
		"avatar_url": "https://i2.ytimg.com/i/u0xqt7g2nkdwg8l96VVqiA/1.jpg",
		"image_url": "https://i.ytimg.com/vi/Fanxe0Oi6BE/3.jpg",
		"image_width": 120,
		"image_height": 90,
		"image_caption": "",
		"title": "Ride Through The Country (Revisited) - The making of the album - Colt Ford",
		"body": "Download Ride Through the Country (Revisited) on iTunes today: http://smarturl.it/RTTCRevisitediTunes Watch as Colt Ford and his band bring Colt's classic de...",
		"link_url": "http://www.youtube.com/watch?v=Fanxe0Oi6BE",
		"link_title": ""
	}, {
		"id": 200,
		"network": "facebook",
		"all_text": "watch  mirandalambert and me in our new video for  somethin  bad  now   somethinbad http   t co uk7s5mt09d miranda lambert   country music videos  news  photos  tour dates   cmt smarturl it stay current on new miranda lambert music videos  news  photos  tour dates  and more on cmt com ",
		"post_id": "5240049567_10152497673679568",
		"post_date": "2014-06-25T15:14:36Z",
		"post_type": "text",
		"poster_sn": "Carrie Underwood",
		"poster_name": "",
		"poster_id": "5240049567",
		"avatar_url": "https://graph.facebook.com/5240049567/picture",
		"image_url": "",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "Watch @mirandalambert and me in our new video for \"Somethin' Bad\" now! #somethinbad http://t.co/uK7s5mt09d",
		"link_url": "http://t.co/uK7s5mt09d",
		"link_title": "Miranda Lambert | Country Music Videos, News, Photos, Tour Dates | CMT"
	}, {
		"id": 199,
		"network": "facebook",
		"all_text": "click  watch  repeat  check out me and  mirandalambert now in our video for  somethin  bad    somethinbad http   t co tmr6tgt6ug carrie underwood   country music videos  news  photos  tour dates   cmt cmt com stay current on new carrie underwood music videos  news  photos  tour dates  and more on cmt com ",
		"post_id": "5240049567_10152497714029568",
		"post_date": "2014-06-25T15:40:38Z",
		"post_type": "text",
		"poster_sn": "Carrie Underwood",
		"poster_name": "",
		"poster_id": "5240049567",
		"avatar_url": "https://graph.facebook.com/5240049567/picture",
		"image_url": "",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "Click. Watch. Repeat! Check out me and @mirandalambert now in our video for \"Somethin' Bad!\" #SomethinBad http://t.co/tMR6tGT6Ug",
		"link_url": "http://t.co/tMR6tGT6Ug",
		"link_title": "Carrie Underwood | Country Music Videos, News, Photos, Tour Dates | CMT"
	}, {
		"id": 201,
		"network": "facebook",
		"all_text": "more info on  the big revival  courtesy of billboard  kenny chesney unveils  the big revival  album cover  exclusive www billboard com country superstar kenny chesney will return this september with a new studio album   the big revival   and the veteran singer songwriter has reveal",
		"post_id": "6070248875_10152438754153876",
		"post_date": "2014-07-14T14:15:20Z",
		"post_type": "photo",
		"poster_sn": "Kenny Chesney",
		"poster_name": "",
		"poster_id": "6070248875",
		"avatar_url": "https://graph.facebook.com/6070248875/picture",
		"image_url": "http://www.billboard.com/files/media/kenny-chesney-the-big-revival-background-billboard-2014-650x430.jpg",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "More info on \"The Big Revival\" courtesy of Billboard.",
		"link_url": "http://www.billboard.com/articles/columns/the-615/6157551/kenny-chesney-big-revival-album-cover-artwork",
		"link_title": "Kenny Chesney Unveils 'The Big Revival' Album Cover: Exclusive"
	}, {
		"id": 195,
		"network": "twitter",
		"all_text": "WI TICKET UPDATE:There are still a few tickets left for the 4-day country event of the year, don't miss out! If ... http://t.co/W7gbItcX3N",
		"post_id": "464875743789744128",
		"post_date": "2014-05-09T21:13:08Z",
		"post_type": "text",
		"poster_sn": "countrythunder",
		"poster_name": "Country Thunder",
		"poster_id": "21697344",
		"avatar_url": "http://pbs.twimg.com/profile_images/378800000731646102/474ca344c0092cd5c7f25555b4197da5_normal.png",
		"image_url": "",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "WI TICKET UPDATE:There are still a few tickets left for the 4-day country event of the year, don't miss out! If ... <a href=\"http://t.co/W7gbItcX3N\" target=\"_blank\">ift.tt/RwIsvm </a>",
		"link_url": "",
		"link_title": ""
	}, {
		"id": 198,
		"network": "facebook",
		"all_text": "happy 4th of july everybody    let freedom ring throughout this great country of ours  have fun and be safe with the cookouts and fireworks ",
		"post_id": "5240049567_10152519049099568",
		"post_date": "2014-07-04T14:28:35Z",
		"post_type": "text",
		"poster_sn": "Carrie Underwood",
		"poster_name": "",
		"poster_id": "5240049567",
		"avatar_url": "https://graph.facebook.com/5240049567/picture",
		"image_url": "",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "Happy 4th of July everybody!!! Let freedom ring throughout this great country of ours! Have fun and be safe with the cookouts and fireworks!",
		"link_url": "",
		"link_title": ""
	}, {
		"id": 193,
		"network": "twitter",
		"all_text": "Attention Wisconsin CT NATION! - Country Thunder Reveals Fresh Lineup at \"The Listening Room,\" Brought to You by... http://t.co/eOt5dSWDAr",
		"post_id": "469554036992393216",
		"post_date": "2014-05-22T19:03:00Z",
		"post_type": "text",
		"poster_sn": "countrythunder",
		"poster_name": "Country Thunder",
		"poster_id": "21697344",
		"avatar_url": "http://pbs.twimg.com/profile_images/378800000731646102/474ca344c0092cd5c7f25555b4197da5_normal.png",
		"image_url": "",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "Attention Wisconsin CT NATION! - Country Thunder Reveals Fresh Lineup at \"The Listening Room,\" Brought to You by... <a href=\"http://t.co/eOt5dSWDAr\" target=\"_blank\">ow.ly/x9IXj </a>",
		"link_url": "",
		"link_title": ""
	}, {
		"id": 197,
		"network": "facebook",
		"all_text": "this 4th of july holiday weekend  remember to think about the us military service men and women who dedicate themselves to keeping our country safe  purchase the  keepussafe track and all proceeds will go to the acm s lifting lives charity  http   smarturl it cukeepussafe \n\nin case you missed it on   academyofcountrymusic presents  an all star salute to the troops  here is carrie’s moving performance of the song  http   smarturl it keepussafevideo iqid facebook",
		"post_id": "5240049567_10152519122554568",
		"post_date": "2014-07-04T15:09:06Z",
		"post_type": "photo",
		"poster_sn": "Carrie Underwood",
		"poster_name": "",
		"poster_id": "5240049567",
		"avatar_url": "https://graph.facebook.com/5240049567/picture",
		"image_url": "https://fbcdn-sphotos-e-a.akamaihd.net/hphotos-ak-xpa1/t1.0-9/p540x540/10516671_10152519121934568_8178504231379008194_n.jpg",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "This 4th of July holiday weekend, remember to think about the US military service men and women who dedicate themselves to keeping our country safe. Purchase the #KeepUsSafe track and all proceeds will go to the ACM's Lifting Lives charity: http://smarturl.it/CuKeepUsSafe \n\nIn case you missed it on  @AcademyOfCountryMusic Presents: An All-Star Salute To The Troops, here is Carrie’s moving performance of the song: http://smarturl.it/keepussafevideo?IQid=facebook",
		"link_url": "https://www.facebook.com/photo.php?fbid=10152519121934568&set=a.182441419567.123128.5240049567&type=1&relevant_count=1",
		"link_title": ""
	}, {
		"id": 192,
		"network": "twitter",
		"all_text": "I just heard some what WILL be one of the most important albums in country music history... Congratulations and thank you @littlebigtown!!!",
		"post_id": "489251392284942336",
		"post_date": "2014-07-16T03:33:16Z",
		"post_type": "text",
		"poster_sn": "blakeshelton",
		"poster_name": "Blake Shelton",
		"poster_id": "14920785",
		"avatar_url": "http://pbs.twimg.com/profile_images/484437394121183232/kxglaz8f_normal.jpeg",
		"image_url": "",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "I just heard some what WILL be one of the most important albums in country music history... Congratulations and thank you <a href='http://twitter.com/littlebigtown' target='_blank'>@littlebigtown </a>!!!",
		"link_url": "",
		"link_title": ""
	}, {
		"id": 196,
		"network": "twitter",
		"all_text": "CMT Hot 20 Countdown and CMT Radio will be joining us on-site for all things Country Thunder! http://t.co/1uyT59I20q http://t.co/TIZduaqabR",
		"post_id": "464530849946685441",
		"post_date": "2014-05-08T22:22:39Z",
		"post_type": "text",
		"poster_sn": "countrythunder",
		"poster_name": "Country Thunder",
		"poster_id": "21697344",
		"avatar_url": "http://pbs.twimg.com/profile_images/378800000731646102/474ca344c0092cd5c7f25555b4197da5_normal.png",
		"image_url": "",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "CMT Hot 20 Countdown and CMT Radio will be joining us on-site for all things Country Thunder! <a href=\"http://t.co/1uyT59I20q\" target=\"_blank\">ift.tt/1jFQTz0 </a> <a href=\"http://t.co/TIZduaqabR\" target=\"_blank\">ift.tt/1jFQTz0 </a>",
		"link_url": "",
		"link_title": ""
	}, {
		"id": 194,
		"network": "twitter",
		"all_text": "As Country Thunder 2014 approaches, We wanted to send a reminder that Travel Packages are still available!\n\nIf y... http://t.co/N2TOVdJyIO",
		"post_id": "465891390837522432",
		"post_date": "2014-05-12T16:28:58Z",
		"post_type": "text",
		"poster_sn": "countrythunder",
		"poster_name": "Country Thunder",
		"poster_id": "21697344",
		"avatar_url": "http://pbs.twimg.com/profile_images/378800000731646102/474ca344c0092cd5c7f25555b4197da5_normal.png",
		"image_url": "",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "As Country Thunder 2014 approaches, We wanted to send a reminder that Travel Packages are still available!\n\nIf y... <a href=\"http://t.co/N2TOVdJyIO\" target=\"_blank\">ift.tt/1jcNfyy </a>",
		"link_url": "",
		"link_title": ""
	}, {
		"id": 180,
		"network": "facebook",
		"all_text": "make sure to check out the exclusive photos from the set of  like a cowboy  over at taste of country   randy houser saddles up for ‘like a cowboy’ video – exclusive pictures tasteofcountry com the new video for randy houser s  like a cowboy  will find the singer as far from his natural habitat as one could imagine  or so it d seem  houser plays a drover in the new clip  an all star casts surrounds him  but it s the mississippi born singer s handling of a horse and a herd that will leave f…",
		"post_id": "49064345453_10154377157685454",
		"post_date": "2014-06-28T02:14:22Z",
		"post_type": "photo",
		"poster_sn": "Randy Houser",
		"poster_name": "",
		"poster_id": "49064345453",
		"avatar_url": "https://graph.facebook.com/49064345453/picture",
		"image_url": "http://wac.450f.edgecastcdn.net/80450F/tasteofcountry.com/files/2014/06/Houser.jpg?w=600&h=0&zc=1&s=0&a=t&q=89",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "Make sure to check out the exclusive photos from the set of \"Like A Cowboy\" over at Taste of Country! ",
		"link_url": "http://tasteofcountry.com/randy-houser-like-a-cowboy-video-exclusive-pictures/",
		"link_title": "Randy Houser Saddles Up for ‘Like a Cowboy’ Video – Exclusive Pictures"
	}, {
		"id": 175,
		"network": "youtube",
		"all_text": "music video by jason aldean performing she s country  youtube view counts pre vevo  66668  c  2009 broken bow records  jason aldean   she s country",
		"post_id": "2AZLUohDCGo",
		"post_date": "2014-07-14T23:38:04Z",
		"post_type": "video",
		"poster_sn": "JasonAldeanVEVO",
		"poster_name": "",
		"poster_id": "y5QKpDQC-H3z82Bw6EVFfg",
		"avatar_url": "https://i2.ytimg.com/i/y5QKpDQC-H3z82Bw6EVFfg/1.jpg",
		"image_url": "https://i.ytimg.com/vi/2AZLUohDCGo/3.jpg",
		"image_width": 120,
		"image_height": 90,
		"image_caption": "",
		"title": "Jason Aldean - She's Country",
		"body": "Music video by Jason Aldean performing She's Country. YouTube view counts pre-VEVO: 66668 (C) 2009 Broken Bow Records.",
		"link_url": "http://www.youtube.com/watch?v=2AZLUohDCGo",
		"link_title": ""
	}, {
		"id": 178,
		"network": "facebook",
		"all_text": "what do y all think of the full length music video for  like a cowboy    randy houser   like a cowboy  full length version   like a cowboy   full length version  from how country feels  available here  http   smarturl it howcountyfeels directed by dustin rikert  a team two enterta   ",
		"post_id": "49064345453_10154416228825454",
		"post_date": "2014-07-08T14:48:13Z",
		"post_type": "photo",
		"poster_sn": "Randy Houser",
		"poster_name": "",
		"poster_id": "49064345453",
		"avatar_url": "https://graph.facebook.com/49064345453/picture",
		"image_url": "http://i1.ytimg.com/vi/Gn_m7uFL7xQ/maxresdefault.jpg",
		"image_width": null,
		"image_height": null,
		"image_caption": "",
		"title": "",
		"body": "What do y'all think of the full length music video for \"Like A Cowboy\"? ",
		"link_url": "http://www.youtube.com/watch?v=Gn_m7uFL7xQ",
		"link_title": "Randy Houser - Like a Cowboy (Full Length Version)"
	}, {
		"id": 174,
		"network": "youtube",
		"all_text": "music video by jason aldean performing she s country  live on letterman    c  2012 cbs interactive music group  jason aldean   she s country  live on letterman ",
		"post_id": "MvonZZDfpxw",
		"post_date": "2014-07-06T23:23:09Z",
		"post_type": "video",
		"poster_sn": "JasonAldeanVEVO",
		"poster_name": "",
		"poster_id": "y5QKpDQC-H3z82Bw6EVFfg",
		"avatar_url": "https://i2.ytimg.com/i/y5QKpDQC-H3z82Bw6EVFfg/1.jpg",
		"image_url": "https://i.ytimg.com/vi/MvonZZDfpxw/3.jpg",
		"image_width": 120,
		"image_height": 90,
		"image_caption": "",
		"title": "Jason Aldean - She's Country (Live On Letterman)",
		"body": "Music video by Jason Aldean performing She's Country (Live On Letterman). (C) 2012 CBS INTERACTIVE MUSIC GROUP.",
		"link_url": "http://www.youtube.com/watch?v=MvonZZDfpxw",
		"link_title": ""
	}]
}